// Top world airports dataset
export const AIRPORTS = [
  { code: 'FCO', name: 'Roma Fiumicino', city: 'Roma', country: 'Italia' },
  { code: 'MXP', name: 'Milano Malpensa', city: 'Milano', country: 'Italia' },
  { code: 'LIN', name: 'Milano Linate', city: 'Milano', country: 'Italia' },
  { code: 'BGY', name: 'Bergamo Orio al Serio', city: 'Bergamo', country: 'Italia' },
  { code: 'NAP', name: 'Napoli Capodichino', city: 'Napoli', country: 'Italia' },
  { code: 'VCE', name: 'Venezia Marco Polo', city: 'Venezia', country: 'Italia' },
  { code: 'BLQ', name: 'Bologna Guglielmo Marconi', city: 'Bologna', country: 'Italia' },
  { code: 'CTA', name: 'Catania Fontanarossa', city: 'Catania', country: 'Italia' },
  { code: 'PMO', name: 'Palermo Falcone Borsellino', city: 'Palermo', country: 'Italia' },
  { code: 'TRN', name: 'Torino Caselle', city: 'Torino', country: 'Italia' },
  { code: 'PSA', name: 'Pisa Galileo Galilei', city: 'Pisa', country: 'Italia' },
  { code: 'FLR', name: 'Firenze Peretola', city: 'Firenze', country: 'Italia' },
  { code: 'LHR', name: 'London Heathrow', city: 'Londra', country: 'UK' },
  { code: 'LGW', name: 'London Gatwick', city: 'Londra', country: 'UK' },
  { code: 'STN', name: 'London Stansted', city: 'Londra', country: 'UK' },
  { code: 'CDG', name: 'Paris Charles de Gaulle', city: 'Parigi', country: 'Francia' },
  { code: 'ORY', name: 'Paris Orly', city: 'Parigi', country: 'Francia' },
  { code: 'AMS', name: 'Amsterdam Schiphol', city: 'Amsterdam', country: 'Paesi Bassi' },
  { code: 'FRA', name: 'Frankfurt Main', city: 'Francoforte', country: 'Germania' },
  { code: 'MUC', name: 'München Franz Josef Strauss', city: 'Monaco', country: 'Germania' },
  { code: 'BER', name: 'Berlin Brandenburg', city: 'Berlino', country: 'Germania' },
  { code: 'BCN', name: 'Barcelona El Prat', city: 'Barcellona', country: 'Spagna' },
  { code: 'MAD', name: 'Madrid Barajas', city: 'Madrid', country: 'Spagna' },
  { code: 'PMI', name: 'Palma de Mallorca', city: 'Palma di Maiorca', country: 'Spagna' },
  { code: 'AGP', name: 'Málaga Costa del Sol', city: 'Malaga', country: 'Spagna' },
  { code: 'VLC', name: 'Valencia', city: 'Valencia', country: 'Spagna' },
  { code: 'SVQ', name: 'Sevilla', city: 'Siviglia', country: 'Spagna' },
  { code: 'ATH', name: 'Athens Eleftherios Venizelos', city: 'Atene', country: 'Grecia' },
  { code: 'HER', name: 'Heraklion Nikos Kazantzakis', city: 'Heraklion', country: 'Grecia' },
  { code: 'SKG', name: 'Thessaloniki Macedonia', city: 'Salonicco', country: 'Grecia' },
  { code: 'PRG', name: 'Prague Václav Havel', city: 'Praga', country: 'Rep. Ceca' },
  { code: 'VIE', name: 'Vienna International', city: 'Vienna', country: 'Austria' },
  { code: 'ZRH', name: 'Zurich', city: 'Zurigo', country: 'Svizzera' },
  { code: 'GVA', name: 'Geneva', city: 'Ginevra', country: 'Svizzera' },
  { code: 'BRU', name: 'Brussels', city: 'Bruxelles', country: 'Belgio' },
  { code: 'LIS', name: 'Lisbon Humberto Delgado', city: 'Lisbona', country: 'Portogallo' },
  { code: 'OPO', name: 'Porto Francisco Sá Carneiro', city: 'Porto', country: 'Portogallo' },
  { code: 'WAW', name: 'Warsaw Chopin', city: 'Varsavia', country: 'Polonia' },
  { code: 'BUD', name: 'Budapest Ferenc Liszt', city: 'Budapest', country: 'Ungheria' },
  { code: 'DUB', name: 'Dublin', city: 'Dublino', country: 'Irlanda' },
  { code: 'ARN', name: 'Stockholm Arlanda', city: 'Stoccolma', country: 'Svezia' },
  { code: 'CPH', name: 'Copenhagen Kastrup', city: 'Copenaghen', country: 'Danimarca' },
  { code: 'OSL', name: 'Oslo Gardermoen', city: 'Oslo', country: 'Norvegia' },
  { code: 'HEL', name: 'Helsinki Vantaa', city: 'Helsinki', country: 'Finlandia' },
  { code: 'IST', name: 'Istanbul', city: 'Istanbul', country: 'Turchia' },
  { code: 'SAW', name: 'Istanbul Sabiha Gökçen', city: 'Istanbul', country: 'Turchia' },
  { code: 'DXB', name: 'Dubai International', city: 'Dubai', country: 'UAE' },
  { code: 'AUH', name: 'Abu Dhabi', city: 'Abu Dhabi', country: 'UAE' },
  { code: 'DOH', name: 'Hamad International', city: 'Doha', country: 'Qatar' },
  { code: 'JFK', name: 'New York John F. Kennedy', city: 'New York', country: 'USA' },
  { code: 'EWR', name: 'New York Newark', city: 'New York', country: 'USA' },
  { code: 'LAX', name: 'Los Angeles', city: 'Los Angeles', country: 'USA' },
  { code: 'ORD', name: "Chicago O'Hare", city: 'Chicago', country: 'USA' },
  { code: 'MIA', name: 'Miami', city: 'Miami', country: 'USA' },
  { code: 'SFO', name: 'San Francisco', city: 'San Francisco', country: 'USA' },
  { code: 'BOS', name: 'Boston Logan', city: 'Boston', country: 'USA' },
  { code: 'NRT', name: 'Tokyo Narita', city: 'Tokyo', country: 'Giappone' },
  { code: 'HND', name: 'Tokyo Haneda', city: 'Tokyo', country: 'Giappone' },
  { code: 'KIX', name: 'Osaka Kansai', city: 'Osaka', country: 'Giappone' },
  { code: 'ICN', name: 'Seoul Incheon', city: 'Seoul', country: 'Corea del Sud' },
  { code: 'PEK', name: 'Beijing Capital', city: 'Pechino', country: 'Cina' },
  { code: 'PVG', name: 'Shanghai Pudong', city: 'Shanghai', country: 'Cina' },
  { code: 'HKG', name: 'Hong Kong', city: 'Hong Kong', country: 'Cina' },
  { code: 'SIN', name: 'Singapore Changi', city: 'Singapore', country: 'Singapore' },
  { code: 'BKK', name: 'Bangkok Suvarnabhumi', city: 'Bangkok', country: 'Tailandia' },
  { code: 'DMK', name: 'Bangkok Don Mueang', city: 'Bangkok', country: 'Tailandia' },
  { code: 'KUL', name: 'Kuala Lumpur', city: 'Kuala Lumpur', country: 'Malaysia' },
  { code: 'CGK', name: 'Jakarta Soekarno-Hatta', city: 'Giacarta', country: 'Indonesia' },
  { code: 'DPS', name: 'Bali Ngurah Rai', city: 'Bali', country: 'Indonesia' },
  { code: 'SYD', name: 'Sydney Kingsford Smith', city: 'Sydney', country: 'Australia' },
  { code: 'MEL', name: 'Melbourne', city: 'Melbourne', country: 'Australia' },
  { code: 'GRU', name: 'São Paulo Guarulhos', city: 'São Paulo', country: 'Brasile' },
  { code: 'GIG', name: 'Rio de Janeiro Galeão', city: 'Rio de Janeiro', country: 'Brasile' },
  { code: 'EZE', name: 'Buenos Aires Ezeiza', city: 'Buenos Aires', country: 'Argentina' },
  { code: 'BOG', name: 'Bogotá El Dorado', city: 'Bogotà', country: 'Colombia' },
  { code: 'LIM', name: 'Lima Jorge Chávez', city: 'Lima', country: 'Perù' },
  { code: 'MEX', name: 'Mexico City', city: 'Città del Messico', country: 'Messico' },
  { code: 'CUN', name: 'Cancún', city: 'Cancún', country: 'Messico' },
  { code: 'CAI', name: 'Cairo', city: 'Il Cairo', country: 'Egitto' },
  { code: 'CPT', name: 'Cape Town', city: 'Città del Capo', country: 'Sud Africa' },
  { code: 'JNB', name: 'Johannesburg OR Tambo', city: 'Johannesburg', country: 'Sud Africa' },
  { code: 'CMN', name: 'Casablanca Mohammed V', city: 'Casablanca', country: 'Marocco' },
  { code: 'RAK', name: 'Marrakech Menara', city: 'Marrakech', country: 'Marocco' },
  { code: 'TUN', name: 'Tunisi Carthage', city: 'Tunisi', country: 'Tunisia' },
];

export function searchAirports(query) {
  const q = query.toLowerCase();
  return AIRPORTS.filter(
    (a) =>
      a.code.toLowerCase().includes(q) ||
      a.name.toLowerCase().includes(q) ||
      a.city.toLowerCase().includes(q) ||
      a.country.toLowerCase().includes(q)
  ).slice(0, 8);
}